name: Just run
on: workflow_dispatch

jobs:
  run-it:
    runs-on: ubuntu-latest
    env:
      MY_MESSAGE: "test env!"
    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: python3 script.py

